<h2>Univariate MultiLayer Perception Model (MLP) Example</h2>

<p>This training demonstrate how to develop a <b>Multilayer Perceptron Model</b> (<b>MLP</b>) for univariate time series forecasting.</p></br>
<p><h3>The plan of attack</h3>
<ul>>> Define a simple univariate problem as a sequence of integers</ul>
<ul>>> Fit the model on this sequence (Train the model)</ul>
<ul>>> Have the model predict the next value in the sequence.</ul></p></br>
<p><h3>Model Explanation:</h3>
<ul>>> Define number of input steps as <code>3</code> via <code>input_dim</code> argument on the first hidden layer.</ul>
<ul>>> We will use efficienct <code>Adam</code> version of stochastic gradient descent.</ul>
<ul>>> Optimize the mean squared error (<code>mse</code>) loss function.</ul></p>

<h3>Full Python Code:</h3>

In [1]:
# Import modules and packages
from numpy import array
from keras.models import Sequential
from keras.layers import Dense

C:\Users\vb100\AppData\Local\conda\conda\envs\deep\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# Define Dataset
X = array([[10, 20, 30], [20, 30, 40], [30, 40, 50], [40, 50, 60]])
y = array([40, 50, 60, 70]) 

In [3]:
print('Independent data (X):\n{}\n\nDependent Data (y):\n{}'.format(X, y))

Independent data (X):
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]]

Dependent Data (y):
[40 50 60 70]


In [4]:
# Define Model
model = Sequential()
model.add(Dense(100, activation = 'relu', input_dim = 3))
model.add(Dense(1))
model.compile(optimizer = 'adam', loss = 'mse')

# Fit Model
model.fit(X, y, epochs = 2000, verbose = 0)

# Demonstrate Prediction
x_input = array([50, 60, 70])
x_input = x_input.reshape((1, 3))
yhat = model.predict(x_input, verbose = 0)[0][0]
print(yhat)

80.55065


<p>© Vytautas Bielinskas, 13 Oct 2018, Lithuania</p>